baseurl = "https://makotokusunoki.com/"
DefaultContentLanguage = "en"
title = "Makoto Kusunoki"
theme = "beautifulhugo"
hasCJKLanguage = true
summaryLength = 190
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
disqusShortname = "makotokusunoki-com"
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"

#googleAnalytics = "XXX"

[Params]
#  homeTitle = "Makoto Kusunoki"
  subtitle = "Works and notes"
  mainSections = ["post","posts"]
  logo = "img/icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  twitter_cards = true
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[markup.goldmark.renderer]
unsafe= true

[markup]
  [markup.tableOfContents]
    startLevel = 2
    ordered = false
    endLevel = 4
   

[Author]
  name = "Makoto Kusunoki"
  twitter = "kusunokiask"
  instagram = "makoto_kusunoki"
  facebook = "kusunokiask"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = -10

[[menu.main]]
    name = "Profile"
    url = "page/profile/"
    weight = -20

[[menu.main]]
    parent = "Gallery"
    name = "Paintings"
    url = "page/paintings/"
    weight = -30

[[menu.main]]
    parent = "Gallery"
    name = "Portraits"
    url = "page/portraits/"
    weight = -40

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 100

[[menu.main]]
    name = "Contact"
    url = "page/contact/"
    weight = 200